from views.location_requests import get_all_locations, get_single_location
from views.animal_requests import get_all_animals, get_single_animal, create_animal
from views.customer_requests import get_all_customers, get_single_customer
from views.employee_requests import get_all_employees, get_single_employee