from views.location_requests import get_all_locations, get_single_location
from views.animal_requests import delete_animal, get_all_animals, get_single_animal, get_animals_by_treatment,get_animals_by_location, delete_animal
from views.animal_requests import update_animal, create_animal
from views.customer_requests import get_all_customers, get_single_customer, get_customers_by_email
from views.employee_requests import get_all_employees, get_single_employee, get_employees_by_location